// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJV0iKC-83I9uSgXm0Rlj2zCS_wrG-gHE',
    appId: '1:383955256385:web:6f1bc3535ffec965f8f2c0',
    messagingSenderId: '383955256385',
    projectId: 'vericode-e9050',
    authDomain: 'vericode-e9050.firebaseapp.com',
    storageBucket: 'vericode-e9050.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtc4cJWWxEotlp9k0sMxivVBfU8zfDG0Q',
    appId: '1:383955256385:ios:f196c68b91f1e4def8f2c0',
    messagingSenderId: '383955256385',
    projectId: 'vericode-e9050',
    storageBucket: 'vericode-e9050.firebasestorage.app',
    iosBundleId: 'com.veridate.barcode.veridateBarcode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtc4cJWWxEotlp9k0sMxivVBfU8zfDG0Q',
    appId: '1:383955256385:ios:f196c68b91f1e4def8f2c0',
    messagingSenderId: '383955256385',
    projectId: 'vericode-e9050',
    storageBucket: 'vericode-e9050.firebasestorage.app',
    iosBundleId: 'com.veridate.barcode.veridateBarcode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJV0iKC-83I9uSgXm0Rlj2zCS_wrG-gHE',
    appId: '1:383955256385:web:093c18491f772fdef8f2c0',
    messagingSenderId: '383955256385',
    projectId: 'vericode-e9050',
    authDomain: 'vericode-e9050.firebaseapp.com',
    storageBucket: 'vericode-e9050.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6iWzDQpWtePzTRxTwJmrEXyZPNxYYlUs',
    appId: '1:383955256385:android:bc271a3b2556ddbdf8f2c0',
    messagingSenderId: '383955256385',
    projectId: 'vericode-e9050',
    storageBucket: 'vericode-e9050.firebasestorage.app',
  );

}